"""
Regenerate requirements.lock from the current Python environment.

Usage
-----
    python scripts/lock_requirements.py

Behaviour
---------
1. Resolve the project root (one level up from this file).
2. Run ``pip freeze`` in the active interpreter's environment.
3. Write the output to ``requirements.lock``, prepending a header comment
   with timestamp and Python version so it's clear when/how it was made.

The script is intentionally minimal — no third-party deps. It only uses the
stdlib so it works in any environment where requirements.txt was installed.
"""
from __future__ import annotations

import datetime as _dt
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK_PATH = ROOT / "requirements.lock"


def main() -> int:
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "freeze", "--all"],
            capture_output=True,
            check=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        print(f"pip freeze failed: {exc.stderr}", file=sys.stderr)
        return 1

    header = (
        "# Auto-generated by scripts/lock_requirements.py — do not edit by hand.\n"
        f"# Generated: {_dt.datetime.now().isoformat(timespec='seconds')}\n"
        f"# Python:    {sys.version.splitlines()[0]}\n"
        "#\n"
        "# Install with:  pip install -r requirements.lock\n"
        "# Regenerate:    python scripts/lock_requirements.py\n"
        "\n"
    )
    LOCK_PATH.write_text(header + result.stdout, encoding="utf-8")
    n_lines = len([l for l in result.stdout.splitlines() if l and not l.startswith("#")])
    print(f"Wrote {n_lines} pinned packages to {LOCK_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
